### ISSUE TITLE
October release plan

### ISSUE THREAD

**Issue by Einingis** [BalticAmadeus/ProPeek#110]
- [x] #54
- [x] #108
- [x] #90
- [x] #97 
- [x] #103 
- [x] #94 
- [x] #95 
- [x] #96

**Comment by PauliusKu** [comment]
Test plan:
- [ ] #54 @Einingis 
- [ ] #108
- [ ] #90
- [ ] #97 @PauliusKu 
- [ ] #103 @PauliusKu 
- [ ] #94 @PauliusKu 
- [ ] #95 @Einingis 
- [ ] #96 @Einingis
