### ISSUE TITLE
Enhancement request : open listing file from propeek

### ISSUE THREAD

**Issue by ccecvb** [BalticAmadeus/ProPeek#155]
The openedge profiler has the ability to generate listing files for the profile session.
The location of those listings is stored in the .prof file.

It would be very nice if propeek was able to visualize those listings.

## Ideas
* Open the listing on correct line when selecting line in the **Line summary**
* Open the top time consuming line of a source when selecting **Module name**
* Alternatives to selecting could be , double clicking, choosing an option from a popup menu

![image](https://github.com/BalticAmadeus/ProPeek/assets/74775499/2efffb27-3696-4daf-8cfc-abf9f8d7467f)

**Comment by PauliusKu** [comment]
Hi @ccecvb, currently we created even better option than listing files - you can open exact code file line. Of course, this requires more setup, as you need to have XREF files generated by VSC ABL extension in specific location, for us to find them.

But, I think, we also can implement listing file linking, as it is not a complicated feature. Then we'll allow user to chose which linking option to use if both will be available.

Thanks for suggestion

**Comment by cverbiest** [comment]
@pauliusku, I have xref files generated by PCT build, would that also work ?
Can I configure where the xref files are located ?

Great idea to have both. 

The exact line in the source code isn't always better. 
We have a lot of include files, when the line is in an include file, the line in itself lacks the context of where that include is used. The listing file has that context.

**Comment by PauliusKu** [comment]
@cverbiest, it is possible to hack your way here. Basically, the extension searches for xref files in `**/.builder/.pct0/` directory.
`const xRefFile = "**/.builder/.pct0/" + fileName + ".xref";`
Also, we need propath, which is taken from **openedge-project.json** file, so you might just add this file with your propath to the root directory of opened VSC instance.
So, if you setup both things, linking should start working even if XREFs were not generated by ABL extension directly.

I think we can definitely improve this in the future and make it easier to set up.

Also, you are right about such cases when listing files might be more useful than program files.
