### ISSUE TITLE
Flame Graph fails without error

### ISSUE THREAD

**Issue by ccecvb** [BalticAmadeus/ProPeek#156]
When using the attached profile file selecting the flame graph clears the propeek page.
* Nothing gets displayed
* No error is shown

I made some string replacements in the profile file to anonymize it a bit.
I don't mind sharing the original file outside of github.

[flamefail.zip](https://github.com/BalticAmadeus/ProPeek/files/14228540/flamefail.zip)

**Comment by PauliusKu** [comment]
Hi, @ccecvb, thanks for the info, we'll have a look into it.

**Comment by cverbiest** [comment]
@PauliusKu When drilling down in a flame graph on one occasion it also hung while a spinner was displayed. Unfortunately, I don't have a reproducible for that now.

**Comment by abelzis** [comment]
@ccecvb You can find [here](https://github.com/BalticAmadeus/ProPeek/releases/tag/1.2.1-prerelease) a `.vsix` file that include the fix for this bug.

To install just right click -> install:
![image](https://github.com/BalticAmadeus/ProPeek/assets/44312404/2df8a358-20e6-446e-beb9-b297b5a4cc28)
